blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = "blog"

# creating urls
urlpatterns = [
    path("app/", BlogListView.as_view(), name="blog_list"),
    path("<str:title>/", BlogDetailView.as_view(), name="blog_detail"),
]
# # creating urls
# urlpatterns = [
#     path('', index),
#     path("app/", blog_list, name="blog_list"),
#     path("<str:title>/", blog_detail, name="blog_detail"),
# ]

blogpr/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("users/", include("users.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# from django.contrib import admin
# from django.urls import path, include

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path("", include("blog.urls")),
# ]

users/urls.py
from django.urls import path
from .views import user_register, user_login, user_logout

app_name = 'users'

urlpatterns = [
    path('register/', user_register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

blog/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=100)
    date_joined = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    
class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date_posted = models.DateField()
    image = models.ImageField(upload_to="images/", blank=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, related_name="posts", null=True)

    def __str__(self):
        return self.title




# from django.db import models

# # Create your models here.
# class Post(models.Model):
#     title = models.CharField(max_length=100)
#     description =models.TextField()
#     date_posted = models.DateField()
#     image = models.ImageField(upload_to="static/img/", blank=True)

#     def __str__(self):
#         return self.title

users/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from .models import Post


# Create your views here.
class BlogListView(ListView):
    model = Post
    template_name = "list.html"
    context_object_name = "posts"
    paginate_by = 3
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.get_queryset(), self.paginate_by)
        context["paginator"] = paginator

        page = self.request.GET.get("page")
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
            
        context["posts"] = posts
        
        return context

    
class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = "detail.html"
    context_object_name = "post"

    def get_object(self):
        return get_object_or_404(Post, title=self.kwargs['title'])











# from django.shortcuts import render, get_object_or_404
# from .models import Post
# # Create your views here.
# def index(request):
#     return render(request, 'index.html')

# def blog_list(request):
#     posts = Post.objects.all()

#     return render(request, "list.html", {"posts": posts})


# def blog_detail(request, title):
    
#     post = get_object_or_404(Post, title=title)
    
#     return render(request, "detail.html", {"post": post})

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages

# Create your views here.
def user_register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect("blog:blog_list")
        else:
            messages.error(request, "Error creating account")
    else:
        form = UserCreationForm()
    
    return render(request, "registration/register.html", {"form": form})


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("blog:blog_list")
        else:
            messages.error(request, "Error logging in")
            
    else:
        form = AuthenticationForm()
        
    return render(request, "registration/login.html", {"form": form})

def user_logout(request):
    logout(request)
    redirect("users:login")

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GIS | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- Bootstrap CDN -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
    />
  </head>
  <body>
    <header>
      <nav
        class="navbar bg-dark border-bottom border-body"
        data-bs-theme="dark"
      >
        <div class="container-fluid">
          <a class="navbar-brand" href="#">GIS</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{%  url 'users:logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}"
                  >Register</a
                >
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="container my-5">{% block content %}{% endblock %}</main>

    <footer class="footer bg-dark text-white fixed-bottom mt-5">
      <div class="row d-flex justify-content-between">
        <div class="p-3">
          <span class="text-start"> Copyright &copy; | 2025 </span>
          <span class="text-end"> Matters Geospatial </span>
        </div>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

blog/templates/detail.html
{% extends 'base.html' %} {% load static %} {% block title %} {{ post.title }}
{% endblock %} {% block content %}

<section>
  <div class="container my-5">
    <h2 class="text-center py-2">{{ post.title }}</h2>
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid" style="max-width: 600px; height: auto; display: block; margin: auto;" />

    <!-- <img src="{{ post.image.url }}" alt="{{ post.title }}" /> -->
    {% endif %}
    <p class="text-muted p-2">
      <i class="fa fa-calendar"></i> {{ post.date_posted|date:"F j, Y" }}
    </p>
    <p class="p-3">{{ post.description }}</p>
    <p class="pb-5">Author: {{ post.author }}</p>
  </div>
</section>

{% endblock %}



<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail_list</title>
</head>
<body>
    <h2>{{post.title}}</h2>
    <p>{{post.date_posted|date:"F j, Y"}}</p>
    <p>{{post.description}}</p> 
</body>
</html> -->
<!-- <section>
    <h2>{{post.title}}</h2>
    <p>{{date_posted|date:"F j, Y"}}</p>
    <p>{{post.description}}</p>

</section> -->

blog/templates/list.html
{% extends 'base.html' %} {% load static %} {% block title %}List{% endblock %}
{% block content %}
<main role="main">
  <div class="hero">
    <img src="{% static 'img/GISDAY.png' %}" alt="" />
  </div>

  <section class="container">
    <ul class="list-unstyled">
      {% for post in posts %}
      <li class="text-muted py-2">
        <i class="fa fa-calendar"></i>
        {{ post.date_posted|date:"F j, Y" }}
      </li>
      <li>
        <a
          href="{% url 'blog:blog_detail' post.title %}"
          class="fw-bold text-decoration-none py-2 text-dark fs-3"
          >{{ post.title}}</a
        >
      </li>
      <li>{{ post.description|truncatewords:30 }}</li>

      <hr class="dotted" />
      {% endfor %}
    </ul>
  </section>

  <section class="container">
    <div class="pagination">
      <span
        class="step-links {% if not posts.has_previous %} disabled {% endif %}"
      >
        <a href="{% url 'blog:blog_list' %}?page=1">first</a>
        {% if posts.has_previous %}
        <a
          href="{% url 'blog:blog_list' %}?page={{ posts.previous_page_number }}"
          >previous</a
        >
        {% endif %}
        <span class="current">
          Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>
        {% if posts.has_next %}
        <a href="{% url 'blog:blog_list' %}?page={{ posts.next_page_number }}"
          >next</a
        >
        {% endif %}

        <a
          href="{% url 'blog:blog_list' %}?page={{ posts.paginator.num_pages }}"
          >last</a
        >
      </span>
    </div>
  </section>
</main>
{% endblock %}



<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog List</title>
</head>
<body>
    <h2>Blog List</h2>

    {% for post in posts %}
    <ul>
        <li>
            <a href="{% url 'blog_detail' post.title %}">{{ post.title }}</a>
        </li>
        <li>{{ post.date_posted|date:"F j, Y" }}</li>
        <li>{{ post.description|truncatewords:40}}</li>
    </ul> 
    {% endfor %}
</body>
</html> -->
<!-- <section>
    <h2>Blog List</h2>

    <ul>
        {% for post in posts %}
        <li>
            <a href="{% url 'blog_detail' post.title %}">{{ post.title }}</a>
        </li>
        <li>{{ post.date_posted|date:"F j, Y" }}</li>
        <li>{{ post.description|truncatewords:40}}</li>
        {% endfor %}
    </ul>





</section> -->